SELECT i.ANIMAL_ID, i.ANIMAL_TYPE, i.NAME
FROM ANIMAL_INS i
JOIN ANIMAL_OUTS o USING (ANIMAL_ID)
WHERE i.SEX_UPON_INTAKE like "Intact%"
AND (o.SEX_UPON_OUTCOME like "Spayed%"
OR o.SEX_UPON_OUTCOME like "Neutered%")
ORDER BY 1
;